### ISSUE TITLE
Commenting on the solution

### ISSUE THREAD

**Issue by merjahe** [msipola/CBM2_course_project_2022#4]
You could now accept the pull request (branch with partner team solution). Remember to comment shortly on the solutions provided by your partner team in your merge commit message!

**Comment by msipola** [comment]
Accepted the PR and commented on the branch. Thank you @aurakiia + team for cooperation and hope to work together soon :D we agree with your solutions and indeed sex seems to have a significant effect on the regression. This would be interesting to study next

Enjoy your summer break (if you have one) and remember to relax!
